name: 'Deploy de projeto vite'
on: 
  push: 
    branches: main
  
jobs: 
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: 'actions/checkout@v4'
      - run: 'npm ci'
      - run: 'npm run build'
      - uses: 'actions/upload-pages-artifact@v3'
        with:
          path: './dist'
  
  test: 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: npx playwright install --with-deps
      - run: npx playwright test
    
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: action/deploy-pages@v4
        id: deployment