name: Integração contínua

on: 
  push: 
    branches:  [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

  Tests:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm ci

      - name: Instalar playwright runner
        run: npx playwright install --with-deps

      - name: Rodar testes
        run: npx playwright test
    